### ISSUE TITLE
Thrown “SCRIPT1028: SCRIPT1028: Expected identifier, string or number” in Edge browser.

### ISSUE THREAD

**Issue by Shawngbk** [sindresorhus/crypto-hash#13]
When using an Angular app which use the @azure/cosmos and run it at Edge browser, it will hit the below error message.
“SCRIPT1028: SCRIPT1028: Expected identifier, string or number”
Clicking the error, I found the error thrown by the line 39.
After search it, found this github link: 
https://github.com/sindresorhus/crypto-hash/blob/master/browser.js#L39
This code is part of the ‘crypto-hash.’

It seems that the ‘crypto-hash’ is required if using the @azure/cosmos.

I search again and found below link which indicating that Edge doesn’t support the Rest parameters (the syntax is ‘…options’)
https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number

Then, the issue seems to be the dead-lock status.
The Angular app use the @azure/cosmos. The @azure/cosmos required the ‘crypto-hash’. ‘crypto-hash’ use the Rest parameters. However, the Edge doesn’t support such syntax..
Therefore, the above restriction let the Angular app cannot be used in the Edge browser.

Could you please look into the issue and consider making change on  '…options’ to make the 'crypto-hash' be compatible with Edge browser as well?

Appreciate it!

**Comment by sindresorhus** [comment]
It's up to you to transpile it with Babel if you want to use it in the browser. I have no intention to add special support for Edge directly here, sorry.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
