### ISSUE TITLE
UMD build?

### ISSUE THREAD

**Issue by chocolateboy** [sindresorhus/crypto-hash#14]
I'd like to [`@require`](https://wiki.greasespot.net/Metadata_Block#.40require) this lovely little library in a userscript, e.g.:

```javascript
// @require https://unpkg.com/crypto-hash@1.2.2
```

\- but that's not possible with the (CommonJS) browser build.

There are [workarounds](https://observablehq.com/@observablehq/how-to-require-stubborn-modules) for this with varying degrees of [inconvenience](https://greasyfork.org/en/scripts/libraries) and [unreliability](https://github.com/Rich-Harris/packd/issues?q=is%3Aissue+is%3Aopen+%22server+error%22), but I thought I'd try to address it at the source first :-)

**Comment by sindresorhus** [comment]
Sorry, I don't intend to add a UMD build to this package.
