### ISSUE TITLE
Browser support (Edge, Safari) - Encoding API

### ISSUE THREAD

**Issue by bayotop** [sindresorhus/crypto-hash#2]
Latest Edge and Safari currently don't implement the [Encoding API](https://encoding.spec.whatwg.org/) and therefore the module won't work:

https://github.com/sindresorhus/crypto-hash/blob/master/browser.js#L17

A fallback as [described here](https://stackoverflow.com/a/36347282/5136654) would be nice.

**Comment by sindresorhus** [comment]
Safari supports it and I don't care about Edge: https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encode
