### ISSUE TITLE
Feature Request: Support es5

### ISSUE THREAD

**Issue by mjfaga** [sindresorhus/crypto-hash#20]
I'm hoping to use this library for some basic hashing functionality in my UI (per https://www.apollographql.com/docs/react/api/link/persisted-queries/#installation), but it doesn't look like this package is built to support es5. 

I am hoping to understand whether or not there is any appetite to do either of the following:
1. introduce a simple build process into the generation of this package
2. re-write the primary module to be explicitly es5 compatible

**Comment by sindresorhus** [comment]
Sorry, no interest in either. It's up to you to use Babel if you need support for older browsers.
