### ISSUE TITLE
Crypto: Subtle Digest Alg not an Object

### ISSUE THREAD

**Issue by llooz** [sindresorhus/crypto-hash#21]
We use this library on a project that has to support legacy web engines (connected TVs) and on Chrome 38 we get errors like
```javascript
TypeError: Failed to execute 'digest' on 'SubtleCrypto': parameter 1 ('algorithm') is not an object.
```

By patching with 
```diff
diff --git a/browser.js b/browser.js
index 0b4337488bdf198c626d6787c3ccb09222d8b171..6165eaf420fce74837f938cb40bcb2ccf07a3c9f 100644
--- a/browser.js
+++ b/browser.js
@@ -44,7 +44,7 @@ const create = algorithm => async (buffer, options) => {
 		...options
 	};
 
-	const hash = await _globalThis.crypto.subtle.digest(algorithm, buffer);
+	const hash = await _globalThis.crypto.subtle.digest({name: algorithm}, buffer);
 
 	return options.outputFormat === 'hex' ? bufferToHex(hash) : hash;
 };

```

we got it working

see https://github.com/ampproject/amphtml/issues/4354

**Comment by sindresorhus** [comment]
Glad you got it working, but I have no intention of supporting such an old browser.

**Comment by LBRDan** [comment]
Hello there
Just a quick question: Why a simple (backward compatible + non breaking + not future limiting + spec compliant) fix cannot be applied to benefit a wider support at no cost?

I also have the same problem as @llooz, on a custom built webkit embedded platform (also not even that old). Not including this fix in a wide used package like this, is prevents more and more packages to be used without a private fork/patch
