### ISSUE TITLE
error Error [ERR_REQUIRE_ESM]: require() 

### ISSUE THREAD

**Issue by kimutaiRop** [sindresorhus/crypto-hash#23]
am trying to use this with sveltekit but I keep getting error 

```Error [ERR_REQUIRE_ESM]: require() of ES Module  Instead change the require of index.js to a dynamic import() which is available in all CommonJS modules ```

am importing this this way `import { sha256 } from 'crypto-hash';`

**Comment by sindresorhus** [comment]
Your build tool is probably transpiring it to `require`.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
