### ISSUE TITLE
Support for older browsers?

### ISSUE THREAD

**Issue by davixyz** [sindresorhus/crypto-hash#25]
Hi! I've been working on an app that uses Apollo Persisted Queries; Unfortunately, we are a little stuck in the past and we could use support for older browsers; Are there plans to support older distributions for these types of clients? maybe a small feature in v1.3.0
https://github.com/sindresorhus/crypto-hash/tree/v1.3.0

**Comment by sindresorhus** [comment]
No plans to support older browsers.
