### ISSUE TITLE
Module not found: Can't resolve 'crypto-hash' when running webpack-dev-server

### ISSUE THREAD

**Issue by gvocale** [sindresorhus/crypto-hash#30]
`Module not found: Can't resolve 'crypto-hash'` when running Cypress component test, which relies on `webpack-dev-server`.

Any idea why?

**Comment by gvocale** [comment]
Solved: adding types fixed the issue
```
yarn add -D @types/crypto-hash
```

**Comment by sindresorhus** [comment]
Closing as it's a problem with Webpack or Webpack config, not this package.
