### ISSUE TITLE
support `md5` or export `create` 

### ISSUE THREAD

**Issue by safareli** [sindresorhus/crypto-hash#31]
Even tho md5 is not secure it's still useful in some settings. would be nice to add it or export the create function

**Comment by sindresorhus** [comment]
MD5 is not natively supported by browsers, so it would only work in Node.js, which doesn't make much sense as this the purpose of this package is to be able to use it in both browsers and Node.js

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#parameters

If you need something non-secure, `SHA-1` is a faster and better alternative anyway.

---

However, I do have a package for this: https://github.com/sindresorhus/md5-hex

**Comment by safareli** [comment]
I wanted something on node which is non blocking so that wouldn't work.

if you were to export `create` that would have been nice.
